services:
    web:
        image: nginx:latest
        container_name: feedback_service_web
        ports:
            - "8800:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - feedback_service

    app:
        container_name: feedback_service_app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        environment:
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - db
        networks:
            - feedback_service

    db:
        container_name: feedback_service_db
        image: postgres:latest
        environment:
            POSTGRES_DB: feedback_service
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5435:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - feedback_service

volumes:
    db_data:

networks:
    feedback_service: